import { ICandidate } from '../types/candidate';

export const mockCandidate: ICandidate = {
  otherRevenuesType: '',
  contractType: 'CDI',
  firstName: 'Fabrice',
  lastName: 'Bricard',
  email: 'fabien.bricard@mail.com',
  dateOfBirth: '1990-01-01T00:00:00.000Z',
  address: '123 Maple Street',
  monthlyJobRevenues: 3500,
  otherRevenues: 0,
  job: 'Software Engineer',
  coCandidates: ['1', '2'],
  maritalStatus: 'single',
  guarantorIds: [
    {
      firstName: 'Michel',
      lastName: 'Bricard',
      email: 'michel.bricard@mail.com',
      dateOfBirth: '1960-03-30T00:00:00.000Z',
      address: '321 Birch Road',
      monthlyJobRevenues: 7000,
      job: 'Medecin',
      contractType: 'Freelance',
      otherRevenues: 3000,
      otherRevenueType: 'rente',
      maritalStatus: 'married',
      phoneNumber: '+33 3 56 87 22 88',
      livingArrangements: 'colocation',
    },
    {
      firstName: 'Sandrine',
      lastName: 'Brichard',
      email: 'sandrine.bricard@mail.com',
      dateOfBirth: '1975-11-05T00:00:00.000Z',
      address: '654 Elm Place',
      monthlyJobRevenues: 4700,
      job: "Chef d'entreprise",
      maritalStatus: 'married',
      contractType: 'CDI',
      otherRevenues: 0,
      phoneNumber: '+33 3 43 32 22 15',
      livingArrangements: 'colocation',
    },
  ],
  workingSince: '2022-01-01T00:00:00.000Z',
  phoneNumber: '+33 7 78 52 45 94',
};
